on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: [13.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with: 
        always-auth: true
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://npm.pkg.github.com'
        scope: '@jerome-nelson'
    - name: Setup Git Identity
      uses: actions-cyborg/gha-git-credentials@v1
      with:
        name: 'Actions Cyborg'
        email: 'actions-cyborg@gmail.com'
        actor: 'actions-cyborg'
        token: '${{ secrets.GITHUB_TOKEN }}'  
    - name: Install Dependencies
      run: |
        npm config set //npm.pkg.github.com/:_authToken ${NPM_AUTH_TOKEN}
        npm ci
      env:
        NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
    - name: Publish Packages
      run: npm run ci:publish